Add database
Rolik8797/java-filmorate pull request #40
Opened 2023-08-19 10:41 UTC by Rolik8797

2023-08-19 10:44 UTC, Rolik8797 commented
ТЗ11

2023-08-20 07:52 UTC, NikolaiDem requested changes

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired(required = false)
Почему не обязательный параметр?
 Аналогично для остальных контроллеров и сервисов

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> findMostPopular(@RequestParam(defaultValue = "10") String count) {
Для числовых значений лучше использовать Integer вместо String.
Аналогично для остальных методов и контроллеров

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorMessage.java
> +public class ErrorMessage {
Этот класс больше относится к пакету exception

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                       @Autowired(required = false) UserService userService) {
Почему required=false?

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validate(film);
Почему используется кастомная валидация вместо использования аннотаций в dto с @Valid?

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setId(getNextId());
Установка id - это обязанность репозитория

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film == null) {
Это условие лишнее, так как отсутствие фильма сгенерирует исключение в репозитории

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        validate(user);
Почему используется кастомная валидация вместо использования аннотаций с @Valid?

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            friends.add(userStorage.getUser(id));
Здесь избыточные запросы в БД.
Лучше сделать метод в репозитории, который вернет сразу всех юзеров по списку id.
Аналогично для getCommonFriends

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            user.setId(++increment);
Установка id - это обязанность репозитория

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new NotFoundException("Пользователь с идентификатором " +
Это условие лишнее, так как отсутствие фильма сгенерирует исключение в репозитории

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +    private final GenreService genreService;
Репозиторий не должен зависеть от каких-либо других сервисов или репозиториев. Его обязанность - это только CRUD операции

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +            genreService.addFilmGenres(film.getId(), film.getGenres());
Вместо вызова сервиса добавление можно сделать своим запросом через jdbcTemplate

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +                addLike(film.getId(), userId);
Лучше добавлять/удалять лайки с помощью соответствующих эндпоинтов. Поэтому эту фичу можно удалить

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +                addLike(film.getId(), userId);
Лучше добавлять/удалять лайки с помощью соответствующих эндпоинтов. Поэтому эту фичу можно удалить

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +            genreService.addFilmGenres(film.getId(), film.getGenres());
Вместо вызова сервиса добавление можно сделать своим запросом через jdbcTemplate

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +                (List<Genre>) genreService.getFilmGenres(filmId),
Проблема N+1 запроса, запросы жанров отсюда необходимо удалить.
Их лучше установить в FilmService, причем для списка фильмов это нужно сделать одним запросом

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBGenreStorage.java
> +            int existingCount = jdbcTemplate.queryForObject(checkExisting, Integer.class, filmId, genre.getId());
Эта проверка лишняя, потому что в DbFilmStorage жанры всегда удаляются

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBGenreStorage.java
> +                jdbcTemplate.update(insertGenreLine, filmId, genre.getId());
Множественное обновление лучше сделать через batchUpdate(...)

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBUserStorage.java
> +                addFriend(user.getId(), friendId);
Друзей лучше добавлять/модифицировать через соответствующие эндпоинты. Фичу можно удалить

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBUserStorage.java
> +        jdbcTemplate.update(sqlSetFriend, userId, friendId, friendAccepted);
Пусть в таблице существует запись
        userId, friendId, status
        1     , 2       , true
        И отправляются 10 запросов подряд на добавление в друзья пользователем 1 пользователя 2
        Все ли корректно будет работать?

        Пусть в таблице существует запись
        userId, friendId, status
        1     , 2       , true
        И отправляются 10 запросов подряд на добавление в друзья пользователем 2 пользователя 1
        Все ли корректно будет работать?

        Для дружбы между пользователем 1 и пользователем 2 предполагается одна запись в БД или 2?

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +   FilmID      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Все поля лучше именовать в нижнем регистре

2023-08-20 07:52 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +    GenreLineID int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
genreLineId не нужен, первичным ключом является (filmId, genreId)

2023-08-20 11:48 UTC, Rolik8797 commented
ТЗ-11.2

2023-08-20 20:02 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> findMostPopular(@RequestParam(defaultValue = "10") String count) {
Не исправлено

2023-08-20 20:03 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                       @Autowired(required = false) UserService userService) {
Не используется

2023-08-20 20:05 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validate(film);
Не исправлено

2023-08-20 20:05 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setId(getNextId());
Не исправлено

2023-08-20 20:05 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film == null) {
Не исправлено

2023-08-20 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        validate(user);
Не исправлено

2023-08-20 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            friends.add(userStorage.getUser(id));
Не исправлено

2023-08-20 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            user.setId(++increment);
Не исправлено

2023-08-20 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new NotFoundException("Пользователь с идентификатором " +
Не исправлено

2023-08-20 20:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +    private final GenreService genreService;
Не исправлено

2023-08-20 20:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +            genreService.addFilmGenres(film.getId(), film.getGenres());
Не исправлено

2023-08-20 20:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +                addLike(film.getId(), userId);
Не исправлено

2023-08-20 20:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +                addLike(film.getId(), userId);
Не исправлено

2023-08-20 20:07 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +            genreService.addFilmGenres(film.getId(), film.getGenres());
Не исправлено

2023-08-20 20:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +                (List<Genre>) genreService.getFilmGenres(filmId),
Не исправлено

2023-08-20 20:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBGenreStorage.java
> +            int existingCount = jdbcTemplate.queryForObject(checkExisting, Integer.class, filmId, genre.getId());
Не исправлено

2023-08-20 20:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBGenreStorage.java
> +                jdbcTemplate.update(insertGenreLine, filmId, genre.getId());
Не исправлено

2023-08-20 20:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBUserStorage.java
> +                addFriend(user.getId(), friendId);
Не исправлено

2023-08-20 20:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBUserStorage.java
> +        jdbcTemplate.update(sqlSetFriend, userId, friendId, friendAccepted);
Не исправлено

2023-08-22 15:43 UTC, Rolik8797 commented
тз11111111

2023-08-23 12:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film add(@Valid FilmDto filmDto) {
Здесь аннотация Valid не нужна, только в контроллере

2023-08-23 12:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film update(@Valid FilmDto filmDto) {
Здесь аннотация Valid не нужна, только в контроллере

2023-08-23 12:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            friends.add(userStorage.getUser(id));
Не исправлено

2023-08-23 14:48 UTC, NikolaiDem requested changes
Светлана, большая часть замечаний не исправлена.

2023-08-23 15:43 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired(required = false)
убрала

2023-08-23 15:43 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> findMostPopular(@RequestParam(defaultValue = "10") String count) {
поправила на Integer

2023-08-23 15:44 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorMessage.java
> +public class ErrorMessage {
перенесла в exception

2023-08-23 15:44 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                       @Autowired(required = false) UserService userService) {
убрала required=false

2023-08-23 15:45 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validate(film);
сделала FilmDTO с аннотацией @Valid

2023-08-23 15:46 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBUserStorage.java
> +                addFriend(user.getId(), friendId);
фичу выделенную Вами удалила

2023-08-23 15:47 UTC, Rolik8797 commented on src/main/resources/schema.sql
> +   FilmID      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
поправила на нижний регистр

2023-08-23 15:47 UTC, Rolik8797 commented on src/main/resources/schema.sql
> +    GenreLineID int  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
поправила

2023-08-23 15:53 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film add(@Valid FilmDto filmDto) {
убрала

2023-08-23 16:24 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBUserStorage.java
> +        jdbcTemplate.update(sqlSetFriend, userId, friendId, friendAccepted);
Поправила запись. В ней перед вставкой новой записи о дружбе метод будет запрашивать базу данных, чтобы проверить, существует ли запись с парой (userId, FriendID) или (FriendID, userId пользователя). Если запись найдена, она использует существующий статус для обновления дружбы, а если запись не найдена, вставляется новая запись.

2023-08-23 17:51 UTC, Rolik8797 commented
1212121212121212121

2023-08-24 14:16 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setId(getNextId());
поправила

2023-08-24 14:20 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film == null) {
поправила

2023-08-24 18:41 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new NotFoundException("Пользователь с идентификатором " +
поправила

2023-08-24 18:45 UTC, NikolaiDem requested changes
Светлана, отправляю на следующую итерацию

2023-08-24 20:03 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            friends.add(userStorage.getUser(id));
поправила

2023-08-24 20:35 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +                addLike(film.getId(), userId);
поправила

2023-08-24 20:36 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +                addLike(film.getId(), userId);
убрала

2023-08-24 21:06 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBGenreStorage.java
> +            int existingCount = jdbcTemplate.queryForObject(checkExisting, Integer.class, filmId, genre.getId());
!

2023-08-25 05:38 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        validate(user);
поправила

2023-08-25 05:56 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +            genreService.addFilmGenres(film.getId(), film.getGenres());
@Override
public Film updateFilm(Film film) {
    String updateFilmQuery = "update film " +
            "set name = ?, description = ?, releasedate = ?, duration = ?, rate = ?, ratingid = ? " +
            "where filmid = ?";
    jdbcTemplate.update(updateFilmQuery,
            film.getName(),
            film.getDescription(),
            film.getReleaseDate(),
            film.getDuration(),
            film.getRate(),
            film.getMpa().getId(),
            film.getId());

    // Удаление жанров фильма
    String deleteGenresQuery = "delete from film_genres where filmid = ?";
    jdbcTemplate.update(deleteGenresQuery, film.getId());

    // Вставка новых жанров фильма
    if (!film.getGenres().isEmpty()) {
        String insertGenresQuery = "insert into film_genres (filmid, genreid) values (?, ?)";
        for (Genre genre : film.getGenres()) {
            jdbcTemplate.update(insertGenresQuery, film.getId(), genre.getId());
        }
    }

    // Добавление лайков
    if (film.getLikes() != null) {
        String insertLikesQuery = "insert into likes (userid, filmid) values (?, ?)";
        for (Integer userId : film.getLikes()) {
            jdbcTemplate.update(insertLikesQuery, userId, film.getId());
        }
    }

    return getFilm(film.getId());
}

2023-08-25 05:57 UTC, Rolik8797 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBFilmStorage.java
> +            genreService.addFilmGenres(film.getId(), film.getGenres());
@Override
public Film addFilm(Film film) {
    String insertFilmQuery = "insert into film " +
            "(name, description, releasedate, duration, rate, ratingid) " +
            "values (?, ?, ?, ?, ?, ?)";
    
    KeyHolder keyHolder = new GeneratedKeyHolder();
    
    jdbcTemplate.update(connection -> {
        PreparedStatement preparedStatement = connection.prepareStatement(insertFilmQuery, Statement.RETURN_GENERATED_KEYS);
        preparedStatement.setString(1, film.getName());
        preparedStatement.setString(2, film.getDescription());
        preparedStatement.setDate(3, Date.valueOf(film.getReleaseDate()));
        preparedStatement.setLong(4, film.getDuration());
        preparedStatement.setInt(5, film.getRate());
        preparedStatement.setInt(6, Math.toIntExact(film.getMpa().getId()));
        return preparedStatement;
    }, keyHolder);

    int id = Objects.requireNonNull(keyHolder.getKey()).intValue();
    
    if (!film.getGenres().isEmpty()) {
        String insertFilmGenresQuery = "insert into film_genres (filmid, genreid) values (?, ?)";
        for (Genre genre : film.getGenres()) {
            jdbcTemplate.update(insertFilmGenresQuery, id, genre.getId());
        }
    }
    
    return getFilm(id);
}

2023-08-25 06:17 UTC, Rolik8797 commented
поправила все, что пропустило

2023-08-25 23:05 UTC, NikolaiDem approved these changes

2023-09-06 10:00 UTC, merged