новая ветка
Rolik8797/java-filmorate pull request #5
Opened 2023-07-17 13:26 UTC by Rolik8797

2023-07-17 16:39 UTC, NikolaiDem requested changes

2023-07-17 16:39 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +@Getter
Лишняя аннотация

2023-07-17 16:39 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +@ToString
Лишняя аннотация

2023-07-17 16:39 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +@EqualsAndHashCode
Лишняя аннотация

2023-07-17 16:39 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +@ToString
Лишняя аннотация

2023-07-17 16:39 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmReleaseDateValidator.java
> +        return localDate.isAfter(LocalDate.of(1895, 12, 28));
LocalDate.of(1895, 12, 28) лучше вынести в константы

2023-07-17 19:19 UTC, Rolik8797 commented
Поправила

2023-07-18 16:08 UTC, NikolaiDem requested changes

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
Добавить логирование всех эндпоинтов

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Добавить логирование всех эндпоинтов

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Component
Не исправлено

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Map<Integer, Film> getAllFilms() {
Не исправлено

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void validateReleaseDate(Film film, String text) {
Не исправлено

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.debug("{} фильм: {}", text, film.getName());
Не исправлено

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Map<Integer, User> getAllUsers() {
Лучше вернуть List<User>, чтобы не раскрывать детали реализации

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        log.debug("{} пользователь: {}, email: {}", text, user.getName(), user.getEmail());
Не исправлено

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    public boolean equals(Object o) {
Переопределение equals, hashCode и toString избыточно

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    public Map<Integer, User> getUsers() {
Лучше вернуть List<User>

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    public boolean equals(Object o) {
Переопределение equals, hashCode и toString избыточно

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    public static int getId() {
private

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    public Map<Integer, Film> getFilms() {
Лучше вернуть List<Film>

2023-07-18 16:08 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    public static int getId() {
private

2023-07-18 17:14 UTC, Rolik8797 commented
Еще раз поправила)

2023-07-18 17:48 UTC, Rolik8797 commented
новее нового

2023-07-18 17:53 UTC, NikolaiDem approved these changes

2023-07-24 08:02 UTC, merged